//product
export const PRODUCT_GETLIST_START='PRODUCT_GETLIST_START';
export const PRODUCT_GETLIST_SUCCESS='PRODUCT_GETLIST_SUCCESS';
export const PRODUCT_GETLIST_FAIL='PRODUCT_GETLIST_FAIL';

//shoppingCart
export const SHOPPINGCART_ADD='SHOPPINGCART_ADD';
export const SHOPPINGCART_UPDATE='SHOPPINGCART_UPDATE';
export const SHOPPINGCART_DELETE='SHOPPINGCART_DELETE';
export const SHOPPINGCART_DELETE_ALL='SHOPPINGCART_DELETE_ALL';

//orders
export const ORDER_ADD_START='ORDER_ADD_START';
export const ORDER_ADD_SUCCESS='ORDER_ADD_SUCCESS';
export const ORDER_ADD_FAIL='ORDER_ADD_FAIL';

//headerItem
export const SET_SELECTED_KEY ='SET_SELECTED_KEY';



