//product
export const PRODUCT_GETLIST_START='PRODUCT_GETLIST_START';
export const PRODUCT_GETLIST_SUCCESS='PRODUCT_GETLIST_SUCCESS';
export const PRODUCT_GETLIST_FAIL='PRODUCT_GETLIST_FAIL';

//export const SHOPPINGCART_GET='SHOPPINGCART_GET';
export const SHOPPINGCART_ADD='SHOPPINGCART_ADD';
export const SHOPPINGCART_UPDATE='SHOPPINGCART_UPDATE';
export const SHOPPINGCART_DELETE='SHOPPINGCART_DELETE';


