//product
export const PRODUCT_GETLIST_START='PRODUCT_GETLIST_START';
export const PRODUCT_GETLIST_SUCCESS='PRODUCT_GETLIST_SUCCESS';
export const PRODUCT_GETLIST_FAIL='PRODUCT_GETLIST_FAIL';
export const PRODUCT_ADD_START='PRODUCT_ADD_START';
export const PRODUCT_ADD_SUCCESS='PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_FAIL='PRODUCT_ADD_FAIL';
export const PRODUCT_ADD_END='PRODUCT_ADD_END';
export const PRODUCT_SELECTED='PRODUCT_SELECTED';

export const PRODUCT_UPDATE_START='PRODUCT_UPDATE_START';
export const PRODUCT_UPDATE_SUCCESS='PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAIL='PRODUCT_UPDATE_FAIL';
export const PRODUCT_UPDATE_END='PRODUCT_UPDATE_END';

//shoppingCart
export const SHOPPINGCART_ADD='SHOPPINGCART_ADD';
export const SHOPPINGCART_UPDATE='SHOPPINGCART_UPDATE';
export const SHOPPINGCART_DELETE='SHOPPINGCART_DELETE';
export const SHOPPINGCART_DELETE_ALL='SHOPPINGCART_DELETE_ALL';

//orders
export const ORDER_ADD_START='ORDER_ADD_START';
export const ORDER_ADD_SUCCESS='ORDER_ADD_SUCCESS';
export const ORDER_ADD_FAIL='ORDER_ADD_FAIL';

//headerItem
export const SET_SELECTED_KEY ='SET_SELECTED_KEY';

//auth
export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAILD='AUTH_FAILD';
export const AUTH_LOGOUT='AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH='SET_AUTH_REDIRECT_PATH';



